AWSTemplateFormatVersion: '2010-09-09'
Description: Udagram CloudFormation Stack

Parameters:
  VpcId:
    Type: String
    Description: IP range for the VPC 

  PublicSubnetCIDR:
    Type: String
    Description: IP range for the public subnet 

  PrivateSubnetCIDR:
    Type: String
    Description: IP range for the private subnet

Resources:
  # IAM Role to allow EC2 instances to access S3 bucket

  EC2Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: S3BucketAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                 - s3:GetObject
                Resource: arn:aws:s3:::ivy-udagram-bucket

  # Security Group for EC2 instances
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for EC2 instances
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp

  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for the Load Balancer
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
  
   LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-047a51fa27710816e
      InstanceType: t3.medium
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      IamInstanceProfile: !Ref EC2Role
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt-get update -y
          sudo apt-get install apache2 -y
          
          aws s3 cp s3://ivy-udagram-bucket/ivy-travel-blog.zip /var/www/html/
          cd /var/www/html/
          unzip ivy-travel-blog.zip
          rm ivy-travel-blog.zip

          service apache2 start

          echo "<h1> Udagram is up and running! </h1>" /var/www/html/index.html

  

 